In [ ]:
import numpy as np
import tensorflow as tf
import torch


# tensor 생성하기


- float64 정확함

In [ ]:
t = (1,2,3,4,5,6)
a = np.array(t)
print(type(t))
print(type(a))

<class 'tuple'>
<class 'numpy.ndarray'>


In [ ]:
print(a.ndim) #몇차원 어레이인지
print(a.shape) #각차원이 몇개의 숫자로 되어있는지
print(a.itemsize) #바이트 반환
print(a.size)
print(a.dtype)


#인스턴스에 따라서 정보를 나타냄

1
(6,)
8
6
int64


In [ ]:
a = np.array([1.,2.,3.])
print(a.dtype)
a

float64


array([1., 2., 3.])

# 텐서플로우에서의 텐서 생성하기

- 넌파이 기준으로 공부
- ndim dtype shape
- 텐서: 차원을 의미
- 텐서플로우: 32비트


- pyorch에서 tensor생성하기



- numpy의 경우 float64 와  int64
- tensorflow의 경우 float32 와 int32
- torch의 경우 float32와 int4

for i in 값 파악


- 넌파이로 리스트 만들기


- tensor를 특정 값으로 초기화하기
: zeros, ones and full (or fill)


In [ ]:
a=np.zeros((3,2))#defalt dtype  float64
#a=np.zeros(shape=(4,4),dtype=np.unit8)
print(a.dtype)
a

float64


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
xxx=np.eye(3)
print(xxx.dtype)
xxx


float64


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a = np.full((1,3),255) #0이나1이아닌 수 넣을때 사용
print(a.dtype)
a

int64


array([[255, 255, 255]])

In [ ]:
a_tf =tf.fill

- 기존의 tensor와 같은 shape의 새로운 tensor생성
- 기존의 ndarry와 같은 shape를 가지는 ndarray 생성(zeros_like, ones_like, full_like)
- tf의 경우는 다음과 같(zeros_like, ones_like, and fill


*linspace로 적용시킬시
float 64(32가 아님)

*np.empty는 초기화를 안하고 새로운 매트릭스를 생성해냄 (쓰는걸 권하지 않음)

- 난수로 구성된 tensor생성
(numpy.random와 toch->ran([d0[...,dn]), tendorflow->random.)