In [ ]:
import numpy as np
import torch
import tensorflow as tf

for c in [np, torch, tf]:
   print(c.__name__,c.__version__)



numpy 1.25.2
torch 2.2.1+cu121
tensorflow 2.15.0


In [ ]:
ori = [1,2,3,4]
a_np=np.array(ori)
a_torch=torch.tensor(ori)
a_tf=tf.constant(ori)

print(a_np)
print(a_torch)
print(a_tf)

[1 2 3 4]
tensor([1, 2, 3, 4])
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [ ]:
b_np=a_torch.numpy()
b_np

array([1, 2, 3, 4])

In [ ]:
b_np[2]=777
b_np

array([  1,   2, 777,   4])

In [ ]:
a_torch

tensor([  1,   2, 777,   4])

In [ ]:
t = [1,2,3,4]

a_np=np.array(t)

a_torch=torch.tensor(a_np)
a_tf=tf.constant(a_np)


print(a_np)
print(a_torch)
print(a_tf)

[1 2 3 4]
tensor([1, 2, 3, 4])
tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


In [ ]:
a_torch[3]=888
b_np[3]

4

In [ ]:
b_np=a_tf.numpy()
b_np


array([1, 2, 3, 4])

In [ ]:
a_tf

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [ ]:
t=[1,2,3,4]

a_np=np.array(t)
a_torch=torch.tensor(a_np)
a_tf=tf.constant(a_np)

print(a_np)
print(a_torch)
print(a_tf)

a_torch[2] = 777
a_np

b_torch =torch.from_numpy(a_np)
b_torch = 888
a_np

[1 2 3 4]
tensor([1, 2, 3, 4])
tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


array([1, 2, 3, 4])

In [ ]:
a_torch.dtype

torch.int64

In [ ]:
a_torch.to(dtype = torch.float32)

tensor([  1.,   2., 777.,   4.])

In [ ]:
a_torch.dtype

torch.int64

In [ ]:
ori

[1, 2, 3, 4]

In [ ]:
sorted(ori)

[1, 2, 3, 4]

In [ ]:
ori.sort()

In [ ]:
ori=[3,2,1,4]
ori.sort()
ori

[1, 2, 3, 4]

In [ ]:
a=np.arange(0,10,1)
b=a.reshape((2,5))
print(a.shape,id(a))
print(b.shape,id(b))
c=np.reshape(a,(5,2))
print(c.shape,id(c))
c[0,0]=1000
print(a)
print(b)
print(c)

(10,) 138068067005904
(2, 5) 138068064971120
(5, 2) 138068064975536
[1000    1    2    3    4    5    6    7    8    9]
[[1000    1    2    3    4]
 [   5    6    7    8    9]]
[[1000    1]
 [   2    3]
 [   4    5]
 [   6    7]
 [   8    9]]


In [ ]:
a_tensor = tf.range(0,10,1)
b_tensor = tf.reshape(a_tensor,(2,5))
# b_tensor = a_tensor.reshape((2,5)) # not working
print(a_tensor.shape,id(a_tensor))
print(b_tensor.shape,id(b_tensor))

c_tensor = tf.reshape(a_tensor,(5,2))
print(c_tensor.shape,id(c_tensor))

# 변경하고 싶은 위치와 값을 정의
indices = tf.constant([[0, 0]]) # (2, 2) 위치를 변경하고자 함
updates = tf.constant([999]) # 해당 위치에 넣고 싶은 값

# 업데이트 적용
c_tensor = tf.tensor_scatter_nd_update(c_tensor, indices, updates)

print(a_tensor)
print(b_tensor)
print(c_tensor)


(10,) 138068371110928
(2, 5) 138068371105296
(5, 2) 138068371107408
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor(
[[0 1 2 3 4]
 [5 6 7 8 9]], shape=(2, 5), dtype=int32)
tf.Tensor(
[[999   1]
 [  2   3]
 [  4   5]
 [  6   7]
 [  8   9]], shape=(5, 2), dtype=int32)


In [ ]:
a=np.arange(0,12).reshape(3,4)

print(a)
print('===============')
print(f'a[0]  is "{a[0]}"')
print(f'a[0,2]  is "{a[0,2]}"')
print(f'a[0][2]  is "{a[0,2]}"')
print('===============')
print(f'a[1,2:]  is "{a[1,2:]}"')
print(f'a[1,::2]  is "{a[1,::2]}"')
print(f'a[1,::-2]  is "{a[1,::-2]}"')
print(f'a[1,::-1]  is "{a[1,::-1]}"')

print(f'a[1,3:0:-1]  is "{a[1,3:0:-1]}"')




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a[0]  is "[0 1 2 3]"
a[0,2]  is "2"
a[0][2]  is "2"
a[1,2:]  is "[6 7]"
a[1,::2]  is "[4 6]"
a[1,::-2]  is "[7 5]"
a[1,::-1]  is "[7 6 5 4]"
a[1,3:0:-1]  is "[7 6 5]"


In [ ]:
x = np.arange(3*3*3).reshape(3,3,3) * 10

print('original:')
print(x)
print('----------')
print('boolean mask:')
b = x <= 270/2
print(b.shape)
print(b)
print('----------')
print('x <= 135')
print(x[b])
print('----------')
print(x[x<=270/2])
print('----------')
print('----------')
print('x <= 135 | x>= 200')
b1 = b | (x >= 200)
print('----------')
print('boolean mask')
print(b1)
print('----------')
print(x[b1])
print('----------')
print(x[ (x<=270/2) | (x>=200)])

original:
[[[  0  10  20]
  [ 30  40  50]
  [ 60  70  80]]

 [[ 90 100 110]
  [120 130 140]
  [150 160 170]]

 [[180 190 200]
  [210 220 230]
  [240 250 260]]]
----------
boolean mask:
(3, 3, 3)
[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]]]
----------
x <= 135
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130]
----------
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130]
----------
----------
x <= 135 | x>= 200
----------
boolean mask
[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True False]
  [False False False]]

 [[False False  True]
  [ True  True  True]
  [ True  True  True]]]
----------
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 200 210 220 230
 240 250 260]
----------
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 200 210 220 230
 24

In [ ]:
a=np.arange(0,6).reshape(2,3)

print(a)

[[0 1 2]
 [3 4 5]]


In [ ]:
b=a<3
b

array([[ True,  True,  True],
       [False, False, False]])

In [ ]:
c=a[a<3]
c

array([0, 1, 2])

In [ ]:
i=np.where(a<3)
i

(array([0, 0, 0]), array([0, 1, 2]))